name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
categories:
  - title: 💥 Breaking changes
    labels:
      - breaking
  - title: 🚀 New features and improvements
    labels:
      - enhancement
      - feat
      - feature
  - title: 🐛 Bug fixes
    labels:
      - bug
      - fix
  - title: 📦 Dependency updates
    labels:
      - dependencies
      - deps
    collapse-after: 15
  - title: 📝 Documentation updates
    labels:
      - documentation
      - docs
      - doc
  - title: 🌐 Localization and translation
    labels:
      - localization
  - title: 🌐 Community-related changes
    labels:
      - community
  - title: 👻 Maintenance
    labels:
      - chore
      - maintenance
  - title: 🚦 Tests
    labels:
      - test
  - title: ✍ Other changes
exclude-labels:
  - skip-changelog
  - invalid
template: |
  $CHANGES

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'deps'
    branch:
      - '/deps\/.+/'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
